In [1]:
print('?')

?

In [89]:
import datetime as dt

In [1]:
def date_format1(d):
    d = str(d).replace('-','.')
    yyyy = int(d.split('.')[0])
    mm = int(d.split('.')[1])
    dd = int(d.split('.')[2])
    
    this_date = dt.date(yyyy,mm,dd)

    return this_date

In [2]:
def date_format2(d):
    yyyy = int(d[:4])
    mm = int(d[4:6])
    dd = int(d[6:])
    
    this_date = dt.date(yyyy,mm,dd)

    return this_date

In [4]:
import requests
from bs4 import BeautifulSoup
import json
import pandas as pd

url='https://finance.naver.com/world/worldDayListJson.nhn?symbol=SPI@SPX&fdtc=0'
#resp=requests.get(url)

xymd=[]
clos=[]
page=1   


while (1):
    
    params={
        'page':page
    }

    resp=requests.get(url,params=params)
    text=resp.text

    page+=1    

    soup=BeautifulSoup(resp.content,'html.parser')
    
    data=json.loads(text)
    
    i=0
    
    #print(dict(zip(range(len(data[0])),data[0])))
    
    for i in range(len(data)):
        
        #print(data[i]['xymd'])
        
        xymd.append(data[i]['xymd'])
        
        #print(data[i]['clos'])
        clos.append(data[i]['clos'])
        
    if page==442 :
        break

In [172]:
#xymd

In [173]:
#clos

In [91]:
#print(index_list)
#print(columns_list)

In [11]:
df = pd.DataFrame()

In [12]:
df['date']=xymd

In [13]:
df['S&P 500']=clos

In [187]:
#df

In [8]:
df=pd.to_datetime(df['date'])

In [14]:
df

          date  S&P 500
0     20190702  2973.01
1     20190701  2964.33
2     20190628  2941.76
3     20190627  2924.92
4     20190626  2913.78
5     20190625  2917.38
6     20190624  2945.35
7     20190621  2950.46
8     20190620  2954.18
9     20190619  2926.46
10    20190618  2917.75
11    20190617  2889.67
12    20190614  2886.98
13    20190613  2891.64
14    20190612  2879.84
15    20190611  2885.72
16    20190610  2886.73
17    20190607  2873.34
18    20190606  2843.49
19    20190605  2826.15
20    20190604  2803.27
21    20190603  2744.45
22    20190531  2752.06
23    20190530  2788.86
24    20190529  2783.02
25    20190528  2802.39
26    20190524  2826.06
27    20190523  2822.24
28    20190522  2856.27
29    20190521  2864.36
...        ...      ...
4378  20020213  1118.51
4379  20020212  1107.50
4380  20020211  1111.94
4381  20020208  1096.22
4382  20020207  1080.17
4383  20020206  1083.51
4384  20020205  1090.02
4385  20020204  1094.44
4386  20020201  1122.20
4387  20020131  1130.20
4388  20020130  1113.57
4389  20020129  1100.64
4390  20020128  1133.06
4391  20020125  1133.28
4392  20020124  1132.15
4393  20020123  1128.18
4394  20020122  1119.31
4395  20020118  1127.58
4396  20020117  1138.88
4397  20020116  1127.57
4398  20020115  1146.19
4399  20020114  1138.41
4400  20020111  1145.60
4401  20020110  1156.55
4402  20020109  1155.14
4403  20020108  1160.71
4404  20020107  1164.89
4405  20020104  1172.51
4406  20020103  1165.27
4407  20020102  1154.67

[4408 rows x 2 columns]

In [ ]:
pd.merge?

In [52]:
#https://finance.naver.com/sise/sise_index_day.nhn?code=KPI200
#&page=1

import requests
from bs4 import BeautifulSoup

url2='https://finance.naver.com/sise/sise_index_day.nhn?code=KPI200'


page=1
   
날짜_리스트=[]
시세_리스트=[]
모든것=[]

모든것=soup.find_all('tr')

t=[]

while (page>0):
    
    #resp2=requests.get(url2)

    params={
        'page':page
    }
    
    resp2=requests.get(url2,params=params)

    soup2=BeautifulSoup(resp2.content,'html.parser')
    
    모든것=soup2.find_all('tr')
    
    for i in range(len(모든것)):
    
        try:
            날짜_리스트.append(모든것[i].find('td',class_='date').text)
            #시세_리스트.append(모든것[i].find('td',class_='number_1').text)
            #print(모든것[i].find('td',class_='date').text)
        except:
            pass
    
    price=soup2.find_all('td',class_='number_1')
#print(len(price))
#print(price)
    for c in range(len(price)):
   # print(date[c])
        if((c+1)%4==1):
            시세_리스트.append(price[c].text)
    
    page+=1
    
    if page==558:#557 개   558 
        break;

print(시세_리스트)

['272.37', '275.97', '277.27', '277.50', '277.75', '275.53', '275.28', '275.58', '275.48', '276.01', '275.31', '271.36', '270.09', '270.48', '271.13', '272.74', '273.21', '272.10', '268.27', '267.99', '267.66', '268.16', '263.89', '263.93', '261.37', '264.70', '264.40', '264.42', '266.38', '266.65', '266.12', '264.96', '264.35', '265.99', '269.64', '268.57', '268.72', '272.06', '271.00', '280.15', '281.31', '283.67', '286.12', '284.92', '286.79', '281.34', '282.83', '283.70', '286.47', '285.87', '285.89', '285.82', '290.33', '290.62', '289.38', '288.37', '287.42', '287.92', '286.71', '286.38', '286.68', '286.15', '285.65', '281.72', '280.32', '276.48', '275.08', '277.28', '277.60', '277.45', '283.13', '282.38', '279.92', '279.82', '279.93', '279.87', '276.64', '276.00', '277.73', '275.06', '274.84', '278.87', '279.85', '280.45', '282.51', '283.80', '288.76', '287.89', '289.00', '288.74', '288.41', '288.40', '284.91', '285.90', '283.98', '288.68', '284.97', '283.69', '282.10', '281.49', '285.65', '285.79', '285.89', '286.62', '283.00', '281.64', '281.67', '276.61', '273.87', '272.71', '274.00', '273.88', '271.88', '271.23', '269.93', '264.99', '267.13', '265.55', '265.60', '259.65', '261.57', '257.89', '255.77', '258.23', '261.98', '260.57', '260.98', '264.45', '265.06', '264.81', '267.31', '265.18', '266.33', '265.55', '269.41', '268.47', '264.69', '265.35', '268.28', '267.18', '271.49', '273.29', '276.18', '271.35', '274.16', '273.45', '272.08', '269.79', '266.33', '267.76', '268.27', '269.58', '272.31', '271.65', '271.54', '268.88', '269.70', '271.57', '271.33', '272.11', '270.45', '271.57', '270.07', '272.56', '262.95', '264.01', '262.47', '260.19', '262.69', '266.72', '271.36', '272.54', '279.40', '278.63', '277.48', '280.05', '276.90', '277.19', '279.37', '275.15', '287.85', '289.91', '291.28', '291.78', '296.53', '300.17', '300.51', '302.59', '300.81', '299.04', '296.64', '296.10', '295.23', '297.29', '292.42', '292.35', '292.46', '293.70', '292.86', '294.28', '294.96', '298.80', '297.49', '300.07', '298.05', '298.05', '297.22', '296.83', '295.54', '294.29', '293.00', '291.93', '288.61', '288.57', '288.24', '291.08', '289.85', '293.64', '297.41', '297.19', '297.18', '295.24', '295.61', '293.55', '298.69', '297.45', '297.29', '297.78', '296.95', '294.85', '295.49', '294.56', '296.95', '295.90', '296.47', '296.88', '297.37', '298.65', '294.41', '294.43', '296.19', '295.20', '293.11', '291.63', '292.26', '293.35', '292.93', '299.66', '298.26', '302.25', '302.76', '303.37', '303.69', '301.02', '304.02', '301.35', '305.35', '308.73', '311.20', '316.84', '317.22', '314.97', '317.67', '315.76', '314.84', '313.22', '310.92', '309.26', '316.20', '318.99', '318.05', '317.48', '318.31', '316.25', '315.37', '314.29', '315.97', '314.94', '317.72', '318.51', '317.31', '314.42', '315.87', '316.75', '320.55', '322.53', '323.56', '320.80', '318.08', '313.99', '315.86', '317.89', '317.89', '320.12', '318.64', '314.64', '315.17', '314.86', '313.22', '312.94', '313.94', '313.45', '311.61', '313.04', '308.54', '313.38', '314.00', '314.61', '313.82', '311.81', '316.34', '314.89', '312.42', '323.32', '321.60', '321.79', '320.35', '322.88', '322.74', '321.99', '322.98', '320.70', '317.67', '314.78', '311.14', '310.46', '304.58', '308.35', '312.86', '316.83', '317.34', '316.81', '312.17', '314.47', '312.83', '316.61', '314.40', '310.87', '308.13', '304.83', '311.62', '310.48', '318.01', '323.29', '327.01', '333.36', '333.38', '333.40', '338.05', '335.38', '334.08', '330.91', '330.93', '326.27', '329.52', '329.13', '329.19', '330.02', '327.39', '326.72', '325.67', '327.61', '330.25', '331.28', '328.97', '324.58', '327.13', '326.00', '324.74', '320.25', '318.89', '321.21', '319.72', '325.79', '326.76', '326.60', '326.23', '324.74', '326.18', '324.07', '325.09', '324.68', '323.59', '324.52', '329.61', '328.77', '324.78', '325.25', '330.68', '330.99', '329.53', '335.44', '334.51', '335.49', '333.51', '332.92', '334.18', '334.36', '332.17', '333.62', '334.33', '335.96', '337.14', '337.80', '336.76', '337.40', '338.83', '337.53', '338.76', '333.57', '330.38', '329.23', '326.99', '329.31', '328.96', '329.45', '328.89', '326.47', '328.40', '328.51', '327.82', '327.35', '328.11', '326.12', '322.49', '316.27', '313.85', '313.82', '314.29', '316.40', '316.71', '318.25', '318.48', '318.51', '318.93', '313.69', '312.52', '310.00', '310.42', '309.83', '307.43', '306.97', '303.18', '304.06', '304.19', '307.78', '308.28', '309.65', '308.64', '309.53', '311.21', '310.73', '309.71', '309.34', '308.14', '308.39', '309.02', '307.16', '304.93', '302.72', '308.37', '309.52', '313.40', '313.96', '313.46', '312.29', '317.69', '317.04', '314.60', '314.13', '320.51', '319.46', '320.15', '322.01', '321.79', '320.61', '318.91', '318.65', '318.52', '317.35', '316.35', '313.58', '313.59', '311.46', '310.66', '311.88', '311.77', '310.46', '312.39', '311.76', '312.56', '310.84', '312.12', '311.89', '310.26', '309.47', '307.52', '309.31', '308.61', '306.79', '306.69', '307.95', '308.02', '306.24', '309.38', '306.25', '305.68', '307.33', '307.83', '304.03', '304.67', '304.59', '306.52', '306.96', '305.22', '301.71', '301.36', '300.63', '298.08', '298.47', '299.34', '299.67', '298.87', '298.25', '299.75', '296.19', '299.86', '292.47', '289.65', '287.21', '287.34', '286.78', '285.41', '281.96', '280.05', '277.76', '276.49', '278.23', '278.10', '277.31', '279.12', '276.21', '275.49', '277.21', '279.01', '279.47', '280.74', '280.92', '281.60', '280.64', '281.66', '281.86', '281.25', '280.36', '282.31', '282.81', '282.63', '283.84', '280.75', '281.86', '280.11', '277.89', '277.89', '275.41', '272.29', '271.62', '272.29', '271.87', '270.41', '269.77', '272.65', '270.06', '268.97', '270.38', '272.89', '272.85', '272.11', '269.73', '268.84', '268.93', '268.81', '267.90', '268.81', '268.66', '267.69', '267.72', '268.97', '269.49', '268.85', '268.49', '269.56', '268.09', '270.48', '268.15', '267.30', '267.12', '266.52', '267.70', '267.08', '267.37', '266.15', '267.91', '269.95', '268.15', '263.73', '263.74', '263.20', '261.98', '263.12', '262.97', '260.36', '260.01', '259.70', '262.49', '261.90', '261.61', '261.97', '262.10', '262.59', '261.93', '262.56', '261.45', '262.00', '261.63', '260.72', '260.91', '262.00', '256.34', '255.63', '252.14', '252.88', '254.48', '254.26', '252.91', '252.96', '252.26', '252.03', '253.66', '252.37', '249.51', '250.21', '250.46', '250.32', '249.20', '250.01', '251.99', '255.31', '249.67', '255.26', '254.60', '252.57', '252.90', '252.83', '255.99', '255.93', '256.53', '256.66', '255.52', '258.57', '259.48', '257.26', '258.41', '258.21', '257.98', '256.19', '255.09', '253.93', '256.20', '256.15', '260.31', '260.06', '261.13', '258.99', '259.18', '257.49', '260.35', '258.21', '259.57', '257.48', '258.37', '258.34', '256.52', '255.09', '253.93', '251.77', '250.53', '257.31', '260.86', '260.31', '260.93', '259.64', '256.50', '256.03', '256.87', '257.49', '256.49', '256.23', '257.26', '257.30', '258.42', '257.27', '258.69', '258.11', '256.04', '256.15', '256.17', '256.18', '255.43', '255.85', '254.11', '252.36', '249.24', '248.65', '251.93', '253.81', '251.48', '251.86', '252.73', '252.72', '250.65', '250.04', '250.44', '250.66', '250.97', '251.52', '251.02', '249.80', '249.25', '247.14', '246.99', '243.43', '244.60', '241.86', '246.91', '247.62', '246.52', '244.14', '242.32', '240.08', '239.28', '239.21', '246.31', '246.75', '245.34', '245.17', '241.63', '241.61', '243.30', '243.35', '244.05', '248.96', '250.19', '250.04', '247.85', '244.39', '244.18', '243.58', '243.63', '241.73', '241.85', '240.58', '240.91', '237.65', '239.85', '238.74', '239.04', '239.82', '241.03', '240.82', '240.60', '242.34', '243.07', '243.68', '242.23', '243.31', '244.29', '243.47', '245.20', '246.27', '248.69', '248.92', '248.13', '248.32', '249.39', '247.26', '247.88', '248.00', '248.53', '248.89', '243.71', '242.06', '241.77', '242.29', '241.99', '240.58', '243.05', '242.36', '245.86', '246.54', '245.53', '243.95', '243.79', '244.08', '245.23', '245.41', '244.28', '244.63', '244.09', '242.35', '241.83', '242.15', '241.97', '241.43', '239.13', '238.44', '240.21', '239.74', '240.09', '238.63', '234.63', '235.22', '235.37', '234.91', '235.03', '234.95', '235.27', '234.74', '231.94', '231.52', '228.40', '224.98', '226.70', '233.30', '232.91', '228.97', '231.10', '233.67', '232.10', '231.51', '230.96', '227.19', '230.21', '228.79', '223.81', '224.54', '230.08', '228.59', '228.78', '231.38', '233.52', '230.55', '230.83', '233.68', '231.93', '234.60', '236.13', '234.63', '240.38', '241.22', '241.79', '245.33', '246.53', '245.48', '243.76', '243.00', '244.17', '243.49', '238.80', '238.17', '240.35', '240.60', '239.40', '239.23', '240.68', '242.15', '244.68', '246.60', '248.70', '244.24', '249.07', '249.43', '246.58', '247.51', '245.92', '244.80', '244.79', '241.44', '241.26', '238.87', '242.71', '245.14', '245.86', '245.86', '249.21', '250.25', '251.79', '252.33', '252.12', '250.60', '249.41', '248.93', '249.79', '250.04', '250.36', '249.41', '247.22', '249.25', '248.53', '247.47', '247.37', '247.89', '244.94', '246.04', '246.49', '246.02', '243.52', '240.18', '237.98', '237.15', '238.62', '236.71', '233.79', '234.26', '234.26', '238.68', '236.72', '241.12', '239.29', '238.78', '233.59', '233.06', '233.74', '237.18', '234.40', '227.76', '227.31', '227.90', '230.40', '229.91', '229.55', '232.80', '232.35', '228.94', '227.71', '223.07', '221.53', '227.14', '231.59', '234.27', '235.20', '235.37', '237.32', '237.24', '237.91', '239.18', '239.79', '240.04', '243.12', '243.55', '241.48', '244.30', '243.61', '245.97', '245.21', '244.98', '244.91', '247.31', '247.88', '250.35', '248.91', '250.23', '251.47', '249.65', '248.64', '249.84', '246.83', '246.77', '244.94', '248.05', '248.30', '254.66', '255.50', '255.07', '252.27', '251.26', '254.48', '253.80', '254.94', '254.52', '250.99', '249.84', '249.67', '249.08', '248.49', '250.74', '251.66', '252.32', '252.11', '253.51', '254.21', '254.94', '255.47', '254.11', '256.29', '258.74', '260.39', '260.06', '260.16', '265.41', '266.03', '262.66', '265.36', '262.92', '261.97', '261.33', '263.69', '263.25', '261.42', '261.49', '260.81', '262.47', '264.03', '267.33', '266.42', '268.03', '268.55', '270.05', '271.05', '272.59', '268.64', '268.17', '268.55', '268.28', '268.45', '265.77', '265.57', '263.48', '261.95', '258.33', '258.51', '256.88', '256.93', '256.75', '254.99', '254.97', '257.28', '256.10', '255.54', '255.99', '258.94', '259.16', '258.95', '258.70', '258.99', '258.22', '258.18', '252.44', '252.18', '250.28', '252.16', '251.75', '252.77', '255.96', '254.16', '254.31', '254.50', '253.65', '251.46', '252.93', '252.96', '251.28', '250.80', '250.37', '249.81', '249.76', '247.71', '248.40', '247.66', '249.26', '250.16', '249.78', '251.60', '250.38', '250.61', '249.88', '250.46', '252.21', '252.20', '250.14', '250.32', '248.47', '248.59', '247.24', '244.78', '242.22', '245.76', '245.99', '246.29', '245.70', '246.05', '243.94', '240.53', '239.93', '244.26', '244.79', '244.05', '246.30', '250.05', '250.07', '249.06', '249.70', '247.96', '243.82', '243.72', '244.43', '246.27', '246.44', '245.54', '249.35', '253.21', '253.71', '254.24', '254.06', '251.65', '251.41', '251.59', '253.70', '253.30', '252.00', '251.72', '252.34', '249.90', '248.96', '250.33', '250.65', '248.30', '248.18', '250.11', '251.26', '250.45', '250.64', '247.39', '247.19', '245.86', '246.51', '248.69', '250.45', '248.84', '248.64', '243.30', '243.89', '242.91', '243.38', '244.12', '241.48', '243.90', '239.84', '242.79', '243.87', '244.47', '244.18', '245.06', '248.36', '249.93', '249.19', '250.06', '252.81', '256.77', '257.95', '258.33', '258.46', '258.88', '258.49', '260.15', '262.31', '261.72', '264.01', '261.45', '260.56', '261.39', '259.80', '262.09', '263.19', '262.27', '262.61', '265.27', '265.41', '266.19', '265.88', '265.14', '264.46', '264.26', '262.53', '266.79', '266.62', '264.24', '265.88', '265.91', '263.34', '263.32', '262.02', '265.64', '266.60', '267.63', '269.65', '268.56', '269.68', '271.17', '268.01', '265.53', '263.47', '262.72', '262.56', '262.86', '261.51', '261.66', '261.93', '260.82', '260.40', '257.27', '256.72', '259.17', '258.87', '259.93', '259.95', '260.63', '261.13', '262.04', '259.74', '260.56', '258.78', '260.03', '258.16', '259.75', '256.77', '255.31', '258.83', '258.70', '260.43', '259.43', '258.75', '262.01', '262.62', '262.64', '259.68', '260.56', '262.22', '261.40', '259.94', '262.57', '263.01', '260.36', '262.33', '263.42', '263.33', '262.40', '263.04', '263.42', '262.97', '262.40', '262.43', '258.40', '255.80', '254.31', '253.84', '252.35', '255.07', '255.33', '255.80', '256.80', '257.42', '261.08', '261.20', '261.55', '260.90', '261.52', '259.66', '259.83', '259.74', '260.51', '260.53', '262.41', '261.21', '260.47', '259.89', '259.47', '259.34', '259.70', '258.95', '258.11', '257.44', '257.26', '255.08', '251.56', '252.31', '250.68', '248.68', '251.32', '251.87', '250.15', '249.02', '251.09', '251.11', '255.49', '254.48', '257.35', '257.63', '257.30', '254.78', '256.29', '258.41', '258.28', '257.31', '256.24', '254.01', '255.22', '250.95', '252.92', '253.66', '253.64', '252.74', '250.97', '252.31', '251.87', '250.47', '250.51', '248.56', '246.04', '245.30', '250.01', '252.89', '249.91', '248.95', '252.89', '253.74', '257.08', '256.34', '254.81', '253.46', '255.36', '254.73', '253.97', '254.08', '252.48', '253.63', '255.76', '255.98', '255.41', '254.48', '257.64', '264.24', '263.32', '263.15', '263.58', '263.24', '261.27', '260.20', '259.98', '258.72', '257.90', '258.04', '259.05', '260.55', '262.68', '263.70', '260.71', '261.10', '261.48', '264.84', '267.58', '269.57', '269.70', '267.15', '266.26', '265.21', '263.86', '262.20', '265.62', '267.81', '265.03', '264.20', '258.44', '258.04', '262.81', '260.15', '260.53', '263.34', '264.62', '264.96', '266.59', '268.63', '266.91', '271.44', '270.28', '269.74', '267.51', '269.36', '268.03', '271.11', '271.22', '271.24', '269.59', '268.25', '269.02', '265.81', '266.35', '262.90', '263.14', '261.85', '261.78', '261.87', '261.48', '260.91', '262.94', '262.68', '261.45', '262.83', '263.02', '262.56', '263.86', '260.83', '262.32', '262.38', '261.20', '258.12', '255.25', '254.62', '252.15', '252.05', '251.13', '251.74', '248.86', '245.67', '245.71', '245.71', '243.37', '240.37', '242.49', '245.13', '248.89', '249.23', '249.82', '248.20', '243.78', '243.13', '243.39', '242.75', '246.80', '248.25', '249.33', '248.89', '247.99', '248.78', '246.53', '247.80', '247.71', '247.84', '246.63', '243.18', '242.03', '242.92', '244.82', '242.02', '243.43', '242.72', '243.88', '236.23', '236.94', '235.12', '237.28', '238.56', '236.63', '240.80', '241.05', '242.27', '238.65', '231.52', '231.75', '233.47', '236.57', '240.26', '245.44', '247.13', '244.77', '245.36', '244.49', '248.50', '250.19', '252.20', '251.20', '256.51', '260.54', '260.29', '261.47', '261.21', '260.92', '258.59', '258.19', '257.32', '256.66', '260.19', '258.18', '258.60', '258.99', '256.60', '256.29', '253.29', '252.72', '257.53', '254.02', '253.84', '255.20', '256.02', '254.92', '255.72', '252.25', '253.04', '254.49', '252.00', '250.01', '251.46', '248.77', '247.85', '251.51', '251.78', '251.51', '252.00', '256.18', '254.34', '252.53', '252.39', '252.77', '257.05', '260.36', '260.79', '262.27', '263.39', '261.86', '261.86', '260.54', '259.58', '255.33', '255.82', '257.04', '259.79', '258.30', '260.84', '263.37', '263.33', '262.43', '264.15', '264.57', '264.78', '267.25', '266.54', '266.14', '268.01', '265.04', '264.68', '266.01', '267.15', '266.85', '268.07', '262.16', '261.63', '261.61', '261.44', '260.92', '256.65', '257.09', '254.00', '254.31', '254.82', '256.89', '257.64', '258.07', '258.47', '257.22', '254.66', '256.06', '258.74', '261.10', '262.91', '261.30', '261.71', '260.10', '260.49', '261.43', '264.80', '263.32', '264.95', '262.90', '263.95', '265.97', '266.14', '267.52', '269.16', '263.92', '262.68', '261.97', '262.11', '261.89', '264.78', '264.23', '262.76', '264.56', '265.79', '261.67', '260.12', '259.03', '258.78', '257.27', '256.63', '254.83', '255.57', '254.25', '254.73', '251.72', '253.41', '250.73', '251.44', '249.51', '247.02', '247.72', '245.82', '243.45', '244.64', '247.80', '246.90', '248.18', '248.69', '250.13', '253.70', '252.30', '249.50', '251.04', '247.83', '250.18', '248.52', '247.66', '247.18', '251.72', '249.80', '251.86', '254.22', '254.79', '257.27', '256.06', '253.98', '251.44', '252.44', '252.84', '255.15', '259.66', '260.11', '262.07', '261.92', '262.48', '262.49', '261.62', '260.42', '262.03', '263.56', '263.41', '261.87', '264.44', '264.25', '263.97', '265.02', '256.87', '256.95', '252.73', '253.38', '254.02', '246.79', '245.75', '250.56', '251.23', '250.56', '250.96', '254.22', '252.57', '252.77', '253.73', '257.28', '256.21', '257.50', '258.03', '258.20', '260.08', '260.11', '256.65', '258.91', '258.08', '252.84', '250.39', '250.36', '244.81', '247.90', '249.60', '250.08', '244.58', '242.23', '235.33', '233.49', '236.65', '235.75', '240.35', '240.44', '236.42', '240.19', '239.39', '238.77', '234.66', '240.34', '240.88', '241.73', '245.07', '247.67', '247.76', '246.80', '244.46', '244.90', '239.98', '239.85', '239.68', '240.75', '244.15', '250.46', '252.92', '251.31', '251.37', '246.57', '248.62', '247.08', '246.43', '248.30', '243.69', '245.51', '238.79', '236.30', '242.98', '244.05', '244.68', '245.26', '241.60', '240.51', '239.76', '242.66', '238.62', '235.85', '244.48', '243.93', '252.32', '254.11', '254.00', '257.89', '258.79', '261.12', '259.73', '264.40', '266.05', '266.61', '264.35', '263.43', '261.51', '260.82', '260.76', '261.66', '261.84', '265.58', '266.22', '263.32', '264.49', '266.86', '263.95', '265.38', '265.88', '269.97', '269.96', '268.33', '272.46', '268.99', '266.58', '267.13', '269.64', '270.71', '267.41', '267.95', '267.98', '267.79', '269.68', '270.27', '268.27', '269.76', '269.85', '266.90', '263.74', '265.62', '262.85', '260.35', '262.85', '264.75', '267.45', '267.13', '263.45', '261.30', '265.20', '263.58', '266.63', '265.89', '265.95', '265.82', '261.89', '265.88', '262.38', '262.75', '261.17', '264.50', '262.94', '259.80', '258.93', '258.53', '260.35', '257.06', '256.90', '255.21', '258.65', '257.52', '257.14', '256.61', '251.27', '247.82', '247.81', '243.10', '245.28', '243.46', '240.83', '241.69', '238.02', '240.57', '243.56', '244.24', '245.82', '238.70', '238.08', '238.15', '240.79', '242.64', '244.22', '241.40', '241.51', '233.83', '231.74', '239.82', '236.72', '242.35', '243.48', '248.55', '244.93', '250.31', '251.57', '249.48', '252.22', '251.19', '251.52', '241.19', '242.50', '236.59', '231.03', '233.35', '231.68', '237.80', '236.64', '239.43', '244.60', '241.98', '246.21', '248.27', '242.99', '236.02', '249.23', '248.32', '250.78', '252.34', '244.09', '248.03', '249.92', '249.88', '252.47', '251.20', '247.56', '247.20', '248.21', '240.02', '235.57', '242.11', '239.89', '243.49', '239.67', '238.09', '236.66', '234.80', '230.82', '230.27', '223.94', '217.34', '221.93', '230.41', '230.37', '223.82', '225.29', '214.18', '218.62', '232.05', '239.51', '237.53', '235.32', '237.50', '228.58', '225.15', '233.40', '238.47', '236.12', '226.65', '228.89', '240.16', '242.37', '242.16', '237.64', '235.78', '229.00', '227.02', '225.14', '228.12', '219.15', '222.98', '238.31', '243.43', '242.23', '230.38', '234.14', '233.23', '233.52', '242.45', '251.90', '261.54', '267.80', '275.40', '282.36', '277.11', '280.04', '282.70', '282.04', '279.66', '282.59', '279.20', '280.41', '276.58', '276.71', '279.59', '278.03', '278.32', '275.90', '282.46', '286.05', '286.07', '285.12', '283.88', '281.67', '278.77', '275.17', '274.61', '270.41', '271.44', '274.31', '269.34', '270.71', '268.65', '264.39', '266.22', '268.88', '274.53', '273.67', '269.79', '269.04', '272.44', '274.46', '276.97', '278.84', '278.76', '282.75', '282.76', '276.32', '277.35', '276.33', '268.62', '271.78', '271.19', '278.59',

In [42]:

date=soup2.find_all('td',class_='date')
print(len(date))
price=soup2.find_all('td',class_='number_1')
#print(len(price))
#print(price)
for c in range(len(price)):
   # print(date[c])
    if((c+1)%4==1):
        print("\n\nThis is ",price[c])

6


This is  <td class="number_1">262.69</td>


This is  <td class="number_1">266.72</td>


This is  <td class="number_1">271.36</td>


This is  <td class="number_1">272.54</td>


This is  <td class="number_1">279.40</td>


This is  <td class="number_1">278.63</td>

In [22]:
print(range(len(모든것)))

for j in range(len(모든것)):
    print(모든것[j].find_all('td',class_='date'))
    print(j)

range(0, 15)
[]
0
[]
1
[<td class="date">2019.07.03</td>]
2
[<td class="date">2019.07.02</td>]
3
[<td class="date">2019.07.01</td>]
4
[]
5
[]
6
[]
7
[<td class="date">2019.06.28</td>, <td class="date">2019.06.27</td>, <td class="date">2019.06.26</td>]
8
[<td class="date">2019.06.28</td>]
9
[<td class="date">2019.06.27</td>]
10
[<td class="date">2019.06.26</td>]
11
[]
12
[]
13
[]
14

#### for i in range(len(모든것)):
    print(모든것[j].find_all('td',class_='date'))
    print(모든것[i].find('td',class_='number_1'))
    print(i)

In [18]:
len(모든것)

15

In [23]:
#날짜_리스트

In [19]:
모든것[:]

[<tr>
 <th>날짜</th>
 <th>체결가</th>
 <th>전일비</th>
 <th>등락률</th>
 <th>거래량<span class="add_txt">(천주)</span></th>
 <th>거래대금<span class="add_txt">(백만)</span></th>
 </tr>, <tr><td class="blank_07" colspan="6"></td></tr>, <tr>
 <td class="date">2006.01.03</td>
 <td class="number_1">178.81</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				0.52
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 red01">
 				+0.29%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">158,041</td>
 <td class="number_1" style="padding-right:30px;">4,161,549</td>
 </tr>, <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>, <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>, <tr><td class="blank_08" colspan="6"></td></tr>, <tr><td class="division_line" colspan="6"></td></tr>, <tr><td class="blank_08" colspan="6"></td></tr>, <tr>
 <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>
 <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>
 <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>
 <tr><td class="blank_09" colspan="6"></td></tr>
 <tr><td class="division_line" colspan="6"></td></tr>
 </tr>, <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>, <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>, <tr>
 <td class="date"> </td>
 <td class="number_1"> </td>
 <td class="rate_down" style="padding-right:35px;"> </td>
 <td class="number_1"> </td>
 <td class="number_1" style="padding-right:40px;"> </td>
 <td class="number_1" style="padding-right:30px;"> </td>
 </tr>, <tr><td class="blank_09" colspan="6"></td></tr>, <tr><td class="division_line" colspan="6"></td></tr>, <tr>
 <td class="pgLL">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=1">
 <img alt="" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarLL.gif" width="7"/>맨앞
 				</a>
 </td>
 <td class="pgL">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=541">
 <img alt="" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarL.gif" width="3"/>이전
 				</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=551">551</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=552">552</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=553">553</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=554">554</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=555">555</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=556">556</a>
 </td>
 <td class="on">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=557">557</a>
 </td>
 </tr>]

In [20]:
시세_리스트

NameError: name '시세_리스트' is not defined

In [53]:
df2 = pd.DataFrame()

In [54]:
df2['date']=날짜_리스트

In [55]:
df2['Kopspi200']=시세_리스트

ValueError: Length of values does not match length of index

In [155]:
#df2['date'] = pd.to_datetime(df2['date'])

In [ ]:
df2.head()

In [ ]:
df2

In [ ]:
df['date'] = pd.to_datetime(df['date'])
df.head()

In [45]:
pd.merge?

In [ ]:
df3 = df.merge(df2, how='outer', left_on='date', right_on='date')
df3

In [83]:
#https://finance.naver.com/sise/sise_index_day.nhn?code=KPI200
#&page=1

import requests
from bs4 import BeautifulSoup

url='https://finance.naver.com/sise/sise_index_day.nhn?code=KPI200'
resp=requests.get(url)

soup=BeautifulSoup(resp.content,'html.parser')


page=1
사전={}
날짜=[]

날짜_리스트=[]
시세_리스트=[]
모든것=[]

모든것=soup.find_all('tr')

t=[]

for i in range(len(모든것)):
    
    try:
        날짜_리스트.append(모든것[i].find('td',class_='date').text)
        시세_리스트.append(모든것[i].find('td',class_='number_1').text)
    except:
        pass


        
    
print(날짜_리스트)
print(시세_리스트)

['2019.07.03', '2019.07.02', '2019.07.01', '2019.06.28', '2019.06.28', '2019.06.27', '2019.06.26']
['272.37', '275.97', '277.27', '277.50', '277.50', '277.75', '275.53']

In [63]:
모든것

[<tr>
 <th>날짜</th>
 <th>체결가</th>
 <th>전일비</th>
 <th>등락률</th>
 <th>거래량<span class="add_txt">(천주)</span></th>
 <th>거래대금<span class="add_txt">(백만)</span></th>
 </tr>, <tr><td class="blank_07" colspan="6"></td></tr>, <tr>
 <td class="date">2019.07.03</td>
 <td class="number_1">272.37</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				3.60
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 nv01">
 				-1.30%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">97,522</td>
 <td class="number_1" style="padding-right:30px;">3,138,322</td>
 </tr>, <tr>
 <td class="date">2019.07.02</td>
 <td class="number_1">275.97</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1.30
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 nv01">
 				-0.47%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">64,740</td>
 <td class="number_1" style="padding-right:30px;">2,670,191</td>
 </tr>, <tr>
 <td class="date">2019.07.01</td>
 <td class="number_1">277.27</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				0.23
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 nv01">
 				-0.08%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">73,429</td>
 <td class="number_1" style="padding-right:30px;">3,276,750</td>
 </tr>, <tr><td class="blank_08" colspan="6"></td></tr>, <tr><td class="division_line" colspan="6"></td></tr>, <tr><td class="blank_08" colspan="6"></td></tr>, <tr>
 <tr>
 <td class="date">2019.06.28</td>
 <td class="number_1">277.50</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				0.25
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 nv01">
 				-0.09%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">66,426</td>
 <td class="number_1" style="padding-right:30px;">2,827,388</td>
 </tr>
 <tr>
 <td class="date">2019.06.27</td>
 <td class="number_1">277.75</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2.22
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 red01">
 				+0.81%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">65,816</td>
 <td class="number_1" style="padding-right:30px;">3,330,708</td>
 </tr>
 <tr>
 <td class="date">2019.06.26</td>
 <td class="number_1">275.53</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				0.25
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 red01">
 				+0.09%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">58,246</td>
 <td class="number_1" style="padding-right:30px;">2,605,449</td>
 </tr>
 <tr><td class="blank_09" colspan="6"></td></tr>
 <tr><td class="division_line" colspan="6"></td></tr>
 </tr>, <tr>
 <td class="date">2019.06.28</td>
 <td class="number_1">277.50</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				0.25
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 nv01">
 				-0.09%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">66,426</td>
 <td class="number_1" style="padding-right:30px;">2,827,388</td>
 </tr>, <tr>
 <td class="date">2019.06.27</td>
 <td class="number_1">277.75</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2.22
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 red01">
 				+0.81%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">65,816</td>
 <td class="number_1" style="padding-right:30px;">3,330,708</td>
 </tr>, <tr>
 <td class="date">2019.06.26</td>
 <td class="number_1">275.53</td>
 <td class="rate_down" style="padding-right:35px;">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				0.25
 				</span>
 </td>
 <td class="number_1">
 <span class="tah p11 red01">
 				+0.09%
 				</span>
 </td>
 <td class="number_1" style="padding-right:40px;">58,246</td>
 <td class="number_1" style="padding-right:30px;">2,605,449</td>
 </tr>, <tr><td class="blank_09" colspan="6"></td></tr>, <tr><td class="division_line" colspan="6"></td></tr>, <tr>
 <td class="on">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=1">1</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=2">2</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=3">3</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=4">4</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=5">5</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=6">6</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=7">7</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=8">8</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=9">9</a>
 </td>
 <td>
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=10">10</a>
 </td>
 <td class="pgR">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=11">
 				다음<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
 </a>
 </td>
 <td class="pgRR">
 <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=557">맨뒤
 				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
 </a>
 </td>
 </tr>]

In [80]:


t=[]

for i in range(len(모든것)):
    
    try:
        t.append(모든것[i].find('td',class_='date').text)
    except:
        pass
        
print(t)

['2019.07.03', '2019.07.02', '2019.07.01', '2019.06.28', '2019.06.28', '2019.06.27', '2019.06.26']

In [ ]:
#모든날짜=soup.find_all('td',class_='date')

while (page>0):  
    
    for i in 모든것: 
        
        날짜.append(i.find('td',class_='date').text)
        print(날짜)
        #책갈피=일별시세.find_next('tr')
        #print(날짜)
    
#        날짜_리스트=날짜.text
    
        일별시세=soup.find('td',class_='number_1')
        #print(일별시세)
    
        사전[날짜.text]=일별시세.text
        일별_리스트=일별시세.text
    
    params={
        'page':page
    }
    resp=requests.get(url,params=params)
    soup=BeautifulSoup(resp.content,'html.parser')
    #print(사전)
    page+=1
    
    if page==20:#557
        break;

print(사전)